name: 'Move Tag'
inputs:
  commitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists.'
    required: true
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
runs:
  using: composite
  steps:
    - name: 'Move Tag'
      run: |
        git tag -fa "${{ inputs.tag_name }}" -m "${{ inputs.tag_name }}" "${{ inputs.commitish }}"
        git push origin "${{ inputs.tag_name }}" --force
      shell: bash
