name: 'Move Tag'
inputs:
  commitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists.'
    required: true
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
runs:
  using: composite
  steps:
    - name: 'Configure git'
      shell: bash
      run: |
        git fetch --tags

        git config user.name "e4-actions-bot"
        git config user.email "e4-actions-bot@users.noreply.github.com"
    - name: 'Move Tag'
      shell: bash
      env:
        TAG_NAME: ${{ inputs.tag_name }}
        COMMITISH: ${{ inputs.commitish }}
      run: |
        TAG_SHA=$(git show-ref refs/tags/$TAG_NAME | cut -d ' ' -f1)
        HEAD_SHA=$(git show-ref refs/heads/$COMMITISH | cut -d ' ' -f1)
        if [ "$TAG_SHA" == "$HEAD_SHA" ]; then
          echo "$TAG_NAME is already set on $COMMITISH"
          exit 0
        fi

        git tag -fa "$TAG_NAME" -m "$TAG_NAME" "$COMMITISH"
        git push origin "$TAG_NAME" --force
