name: 'Auto Tagging'

on:
  push:
    branches:
      - 'release/**'
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  auto-tagging:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Set env for pull request event'
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
        run: |
          COMMITISH="${{ github.base_ref }}"
          echo "COMMITISH=$COMMITISH" >> "$GITHUB_ENV"

          TAG_NAME=$(echo "${{ github.head_ref }}" | sed -e 's/^release\///')
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
      - name: 'Set env for push event'
        if: github.event_name == 'push' && github.ref_type == 'branch' && startsWith(github.ref_name, 'release/')
        run: |
          COMMITISH="${{ github.ref_name }}"
          echo "COMMITISH=$COMMITISH" >> "$GITHUB_ENV"

          TAG_NAME=$(echo "${{ github.ref_name }}" | sed -e 's/^release\///')
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMITISH }}
      - name: 'Configure github actions bot'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: 'Move or create tag'
        uses: E4-Actions/move-tag@develop
        with:
          commitish: ${{ env.COMMITISH }}
          tag_name: ${{ env.TAG_NAME }}
