name: 'Auto Tagging'

on:
  push:
    branches:
      - 'release/**'
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  auto-tagging-for-prerelease:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'branch' && startsWith(github.ref_name, 'release/')
    permissions:
      contents: write

    steps:
      - name: 'Set env'
        run: |
          COMMITISH="${{ github.ref_name }}"
          echo "COMMITISH=$COMMITISH" >> "$GITHUB_ENV"

          TAG_NAME=$(echo "${{ github.ref_name }}" | sed -e 's/^release\///')
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
      - name: 'Create pre-release'
        uses: E4-Actions/create-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commitish: ${{ env.COMMITISH }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: true
          generate_release_notes: true
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMITISH }}
      - name: 'Configure github actions bot'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: 'Move tag'
        uses: ./
        with:
          commitish: ${{ env.COMMITISH }}
          tag_name: ${{ env.TAG_NAME }}
  auto-tagging-for-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
    permissions:
      contents: write

    steps:
      - name: 'Set env'
        run: |
          COMMITISH="${{ github.base_ref }}"
          echo "COMMITISH=$COMMITISH" >> "$GITHUB_ENV"

          TAG_NAME=$(echo "${{ github.head_ref }}" | sed -e 's/^release\///')
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMITISH }}
      - name: 'Configure github actions bot'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: 'Move tag'
        uses: ./
        with:
          commitish: ${{ env.COMMITISH }}
          tag_name: ${{ env.TAG_NAME }}
      - name: 'Update release'
        uses: E4-Actions/update-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commitish: ${{ env.COMMITISH }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: false
