name: 'Release'

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      commitish: ${{ steps.set-variables.outputs.commitish }}
      tag_name: ${{ steps.set-variables.outputs.tag_name }}

    steps:
      - name: 'Set variables'
        id: set-variables
        run: |
          COMMITISH="${{ github.base_ref }}"
          echo "commitish=$COMMITISH" >> "$GITHUB_OUTPUT"

          TAG_NAME=$(echo "${{ github.head_ref }}" | sed -e 's/^release\///')
          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
  move-tag:
    runs-on: ubuntu-latest
    needs: set-variables
    env:
      COMMITISH: ${{ needs.set-variables.outputs.commitish }}
      TAG_NAME: ${{ needs.set-variables.outputs.tag_name }}
    permissions:
      contents: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMITISH }}
      - name: 'Move tag'
        uses: ./
        with:
          commitish: ${{ env.COMMITISH }}
          tag_name: ${{ env.TAG_NAME }}
  update-release:
    runs-on: ubuntu-latest
    needs: set-variables
    env:
      COMMITISH: ${{ needs.set-variables.outputs.commitish }}
      TAG_NAME: ${{ needs.set-variables.outputs.tag_name }}
    permissions:
      contents: write

    steps:
      - name: 'Update release'
        uses: E4-Actions/update-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commitish: ${{ env.COMMITISH }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: false
