name: Test Action

on:
  workflow_dispatch:
    inputs:
      commitish:
        description: 'Commitsh'
        type: string
        required: true
        default: 'master'
      tag_name:
        description: 'Tag'
        type: string
        required: true
        default: 'v0.1.0'
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
          COMMITISH="master"
          [ ! -n ${{ inputs.commitish }} ] && COMMITISH=${{ inputs.commitish }}
          echo "COMMITISH=$COMMITISH" >> $GITHUB_ENV

          TAG_NAME="v0.1.0"
          [ ! -n ${{ inputs.tag_name }} ] && TAG_NAME=${{ inputs.tag_name }}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMITISH }}
      - name: Configure github actions bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Test step
        uses: E4-Actions/move-tag@feature/move-tag
        with:
          commitish: ${{ env.COMMITISH }}
          tag_name: ${{ env.TAG_NAME }}
